version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:

  build-frontend:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build React app
          command: npm run build
      - run:
          name: Run React tests
          command: npm test -- --watchAll=false || echo "No tests yet"

  build-backend:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/repo/backend
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run backend tests
          command: npm test || echo "No tests yet"

  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=TheWilliamsGP_international-bank \
              -Dsonar.organization=thewilliamsgp \
              -Dsonar.sources=src,backend \
              -Dsonar.exclusions=**/node_modules/**,**/build/**,**/dist/** \
              -Dsonar.host.url=https://sonarcloud.io \
              

workflows:
  version: 2
  build_test_analyze:
    jobs:
      - build-frontend
      - build-backend
      - sonar-scan:
          requires:
            - build-frontend
            - build-backend

